BTL_WebBanSach05/BTL_WebBanSach05/Models/GIOHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WebBanSach05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int ID_GIOHANG { get; set; }
        public int ID_KHACHHANG { get; set; }
        public int MASACH { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual TK_KHACHHANG TK_KHACHHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}

BTL_WebBanSach05/BTL_WebBanSach05/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_WebBanSach05.Models;

namespace BTL_WebBanSach05.Controllers
{
    public class HomeController : Controller
    {
        WebBanSachEntities1 db = new WebBanSachEntities1();
        // GET: Home
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.Hoten = "Xin chào " + kh.HOTENKH;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.Hoten = "";
            }
            return View();
        }

        public ActionResult Log()
        {
            Session["TaiKhoan"] = null;
            return RedirectToAction("Index");
        }

        public ActionResult Contact()
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.Hoten = "Xin chào " + kh.HOTENKH;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.Hoten = "";
            }
            return View();
        }
        public ActionResult CTSanPham(int? idSP)
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.Hoten = "Xin chào " + kh.HOTENKH;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.Hoten = "";
            }
            ViewBag.IdSP = idSP;
            return View();
        }
        public ActionResult Filter()
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.Hoten = "Xin chào " + kh.HOTENKH;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.Hoten = "";
            }
            return View();
        }

        public ActionResult GioHang(string idKH)
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.hoTen = kh.HOTENKH;
                ViewBag.SDT = kh.SDT_KH;
                ViewBag.DiaChi = kh.DIACHI;
                ViewBag.HT = "Xin chào " + ViewBag.hoTen;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.hoTen = "";
                ViewBag.HT = "";
            }

            if (idKH == "")
            {
                ViewBag.idKhach = -1;
                ViewBag.ThongBao = "Vui lòng đăng nhập để xem giỏ hàng!";
            }
            else
            {
                ViewBag.idKhach = idKH;
                ViewBag.ThongBao = "";
            }
            return View();
        }

        public ActionResult TTKhach(string idKH)
        {
            if (Session["TaiKhoan"] != null)
            {
                TK_KHACHHANG kh = (TK_KHACHHANG)Session["TaiKhoan"];
                ViewBag.IdKH = kh.ID_KHACHHANG;
                ViewBag.hoTen = kh.HOTENKH;
                ViewBag.SDT = kh.SDT_KH;
                ViewBag.DiaChi = kh.DIACHI;
                ViewBag.HT = "Xin chào " + ViewBag.hoTen;
            }
            else
            {
                ViewBag.IdKH = "";
                ViewBag.hoTen = "";
                ViewBag.HT = "";
            }

            if (idKH == "")
            {
                ViewBag.idKhach = -1;
                ViewBag.ThongBao = "Vui lòng đăng nhập để xem thông tin của bạn!";
            }
            else
            {
                ViewBag.idKhach = idKH;
                ViewBag.ThongBao = "";
            }
            return View();
        }

    }
}

BTL_WebBanSach05/BTL_WebBanSach05/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BTL_WebBanSach05.Models;

namespace BTL_WebBanSach05.Controllers
{
    public class NguoiDungController : Controller
    {
        WebBanSachEntities1 db = new WebBanSachEntities1();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(FormCollection f)
        {
            String sHoten = f.Get("name").ToString();
            String sDiaChi = f.Get("add").ToString();
            String sPhone = f.Get("phone").ToString();
            String sMatKhau = f.Get("password").ToString();

            TK_KHACHHANG kh = db.TK_KHACHHANG.SingleOrDefault(n => n.SDT_KH == sPhone);

            if(kh != null)
            {
                ViewBag.ThongBao = "Đã tồn tại tài khoản! Vui lòng nhập số điện thoại khác!";
                return View();
            }
            else if(sMatKhau.Length < 8 && (sPhone.Length < 10 || sPhone.Length > 10))
            {
                ViewBag.ThongBao = "Số điện thoại và mật khẩu không đúng định dạng!";
                return View();
            }
            else if (sPhone.Length < 10 || sPhone.Length > 10)
            {
                ViewBag.ThongBao = "Số điện thoại cần có 10 số!";
                return View();
            }
            else if (sMatKhau.Length < 8)
            {
                ViewBag.ThongBao = "Mật khẩu cần có 8 ký tự trở lên!";
                return View();
            }
            else if (sPhone != "" && sMatKhau != "" && sHoten != "" && sDiaChi != "")
            {
                TK_KHACHHANG tk = new TK_KHACHHANG();
                tk.HOTENKH = sHoten;
                tk.DIACHI = sDiaChi;
                tk.SDT_KH = sPhone;
                tk.MATKHAU_KH = sMatKhau;

                db.TK_KHACHHANG.Add(tk);
                db.SaveChanges();
                ViewBag.ThongBao = "Đăng ký thành công !!!";
                return RedirectToAction("DangNhap");
            }
            else
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            String sTaiKhoan = f.Get("name").ToString();
            String sMatKhau = f.Get("password").ToString();
            TK_KHACHHANG kh = db.TK_KHACHHANG.SingleOrDefault(n => n.SDT_KH == sTaiKhoan && n.MATKHAU_KH == sMatKhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "đăng nhập thành công";
                Session["TaiKhoan"] = kh;
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ThongBao = "Tài khoản hoặc mật khẩu ko đúng";
            return View();
        }

    }
}

BTL_WebBanSach05/BTL_WebBanSach05/Views/Home/CTSanPham.cshtml
@{
    ViewBag.Title = "CTSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/Content/styles/bootstrap4/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/owl.theme.default.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/animate.css" rel="stylesheet" />
<link href="~/Content/plugins/themify-icons/themify-icons.css" rel="stylesheet" />
<link href="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/styles/single_responsive.css" rel="stylesheet" />
<link href="~/Content/styles/single_styles.css" rel="stylesheet" />


@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetSach();
        });
        function GetSach() {
            var id = 0;
            $.ajax({
                url: "https://localhost:44357/api/SachClient?idSP=@ViewBag.IdSP",
                method: 'GET',
                contentType: 'json',
                dataType: 'json',
                error: function (response) {
                },
                success: function (reponse) {
                    const len = reponse.length;
                    let table = '';
                    for (var i = 0; i < len; ++i) {
                        table = table +
                            '<div class="col-lg-5">' +
                            '<div class="single_product_pics">' +
                            '<div class="row">' +
                            '<div class="col-lg-1 thumbnails_col order-lg-1 order-2">' +
                            '</div>' +
                            '<div class="col-lg-11 image_col order-lg-2 order-1">' +
                            '<div class="single_product_image">' +
                            '<div class="single_product_image_background" style="background-image:url(https://localhost:44357/Areas/Admin/Image/' + reponse[i].TenAnh +')"></div>' +
                            '</div>' +
                            '</div>' +
                            '</div>' +
                            '</div>' +
                            '</div>' +
                            '<div class="col-lg-7">' +
                            '<div class="product_details">' +
                            '<div class="product_details_title">' +
                            '<h2>' + reponse[i].TenSanPham + '</h2>' +
                            '<p>Tác giả: ' + reponse[i].TenTacGia + '</p>' +
                            '<p>Thể loại: ' + reponse[i].TheLoai + '</p>' +
                            '<p>Nhà xuất bản: ' + reponse[i].NXB + '</p>' +
                            '<p>Ngôn ngữ: ' + reponse[i].NGONNGU + '</p>' +
                            '<p>Số trang: ' + reponse[i].SOTRANG + ' trang</p>' +
                            '<p>Kích thước: ' + reponse[i].KICHTHUOC + '</p>' +
                            '<p>Số lượng: ' + reponse[i].SoLuong + ' quyển</p>' +
                            '<div class="product_price">Giá: ' + reponse[i].GIABAN + ' đ</div>' +
                            '<ul class="star_rating">' +
                            '<li><i class="fa fa-star" aria-hidden="true"></i></li>' +
                            '<li><i class="fa fa-star" aria-hidden="true"></i></li>' +
                            '<li><i class="fa fa-star" aria-hidden="true"></i></li>' +
                            '<li><i class="fa fa-star" aria-hidden="true"></i></li>' +
                            '<li><i class="fa fa-star-o" aria-hidden="true"></i></li>' +
                            '</ul>' +
                            '<div class="quantity d-flex flex-column flex-sm-row align-items-sm-center" > ' +
                            '<span > Quantity:</span > ' +
                            '<div class="quantity_selector" > ' +
                            '<span class="minus" > <i class="fa fa-minus" aria-hidden="true"></i></span > ' +
                            '<span id = "quantity_value"> 1 </span > ' +
                            '<span class="plus" > <i class="fa fa-plus" aria-hidden="true"></i></span > ' +
                            '</div>' +
                            '<div class = "red_button" style="padding: 15px; margin-left: 20px;"><a href="#" onclick ="insertGH(' + reponse[i].MaSanPham + ', 1)">add to cart</a></div>' +
                            '<div class="product_favorite d-flex flex-column align-items-center justify-content-center" ></div> ' +
                            '</div>' +
                            '</div>' +
                            '</div>';
                    }
                    document.getElementById('ctsp').innerHTML = table;
                },
                fail: function (response) {
                }
            });
        }
    </script>

    <script type="text/javascript">
        function insertGH(masach, sl) {
            var url = 'https://localhost:44357/api/SachClient?idKH=@ViewBag.idKH&MaSach=' + masach + '&Soluong=' + sl;

            $.ajax({
                url: url,
                method: 'POST',
                contentType: 'json',
                dataType: 'json',
                error: function (response) {
                    alert("Thêm mới không thành công! Vui lòng đăng nhập để thêm sản phẩm vào giỏ hàng!");
                },
                success: function (reponse) {
                    if (reponse == true) {
                        alert("Thêm vào giỏ hàng thành công");
                    }
                    else {
                        alert("Sách đã hết hàng! Bạn không thể thêm vào giỏ hàng!");
                    }
                }
            });
        }
    </script>

}

<header class="header trans_300">

    <!-- Top Navigation -->

    <div class="top_nav">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="top_nav_left">free shipping on all u.s orders over $50</div>
                </div>
                <div class="col-md-6 text-right">
                    <div class="top_nav_right">
                        <ul class="top_nav_menu">

                            <!-- Currency / Language / My Account -->

                            <li class="account">
                                <a href="#">
                                    My Account
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="account_selection">
                                    <li><a href="@Url.Action("DangNhap", "NguoiDung")"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
                                    <li><a href="https://localhost:44357/Home/Log"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign out</a></li>
                                    <li><a href="@Url.Action("DangKy", "NguoiDung")"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Navigation -->

    <div class="main_nav_container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right">
                    <div class="logo_container">
                        <a href="#">book<span>shop</span></a>
                        <p>@ViewBag.Hoten</p>
                    </div>
                    <nav class="navbar">
                        <ul class="navbar_menu">
                            <li><a href="@Url.Action("Index")">home</a></li>
                            <li><a href="@Url.Action("Contact")">contact</a></li>
                        </ul>
                        <ul class="navbar_user">
                            <li><a href="@Url.Action("Filter")"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                            <li><a href="https://localhost:44357/Home/TTKhach?idKH=@ViewBag.IdKH"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                            <li class="checkout">
                                <a href="https://localhost:44357/Home/GioHang?idKH=@ViewBag.IdKH">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    <span id="checkout_items" class="checkout_items">2</span>
                                </a>
                            </li>
                        </ul>
                        <div class="hamburger_container">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container single_product_container">
    <div class="row">
        <div class="col">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">

            </div>

        </div>
    </div>

    <div class="row" id="ctsp">

    </div>

</div>

<script src="~/Content/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/styles/bootstrap4/popper.js"></script>
<script src="~/Content/styles/bootstrap4/bootstrap.min.js"></script>
<script src="~/Content/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="~/Content/plugins/easing/easing.js"></script>
<script src="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="~/Content/js/contact_custom.js"></script>

BTL_WebBanSach05/BTL_WebBanSach05/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/styles/bootstrap4/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/owl.theme.default.css" rel="stylesheet" />
<link href="~/Content/plugins/OwlCarousel2-2.2.1/animate.css" rel="stylesheet" />
<link href="~/Content/plugins/themify-icons/themify-icons.css" rel="stylesheet" />
<link href="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/styles/contact_responsive.css" rel="stylesheet" />
<link href="~/Content/styles/contact_styles.css" rel="stylesheet" />
<script src='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />

<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.css" type="text/css">

<style>
    body {
        margin: 0;
        padding: 0;
    }

    #map {
        width: 100%;
        height: 500px;
    }
</style>
<style>
    .coordinates {
        background: rgba(0, 0, 0, 0.5);
        color: #fff;
        position: absolute;
        bottom: 40px;
        left: 10px;
        padding: 5px 10px;
        margin: 0;
        font-size: 11px;
        line-height: 18px;
        border-radius: 3px;
        display: none;
    }
</style>
<style>
    #buttons {
        width: 90%;
        margin: 0 auto;
    }

    .button {
        display: inline-block;
        position: relative;
        cursor: pointer;
        width: 23%;
        padding: 8px;
        border-radius: 3px;
        margin-top: 20px;
        font-size: 12px;
        text-align: center;
        color: #fff;
        background: #ee8a65;
        font-family: sans-serif;
        font-weight: bold;
    }
</style>

<header class="header trans_300">

    <!-- Top Navigation -->

    <div class="top_nav">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="top_nav_left">free shipping on all u.s orders over $50</div>
                </div>
                <div class="col-md-6 text-right">
                    <div class="top_nav_right">
                        <ul class="top_nav_menu">

                            <!-- Currency / Language / My Account -->

                            <li class="account">
                                <a href="#">
                                    My Account
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="account_selection">
                                    <li><a href="@Url.Action("DangNhap", "NguoiDung")"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
                                    <li><a href="https://localhost:44357/Home/Log"><i class="fa fa-sign-out" aria-hidden="true"></i>Sign out</a></li>
                                    <li><a href="@Url.Action("DangKy", "NguoiDung")"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Navigation -->

    <div class="main_nav_container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right">
                    <div class="logo_container">
                        <a href="#">book<span>shop</span></a>
                        <p>@ViewBag.Hoten</p>
                    </div>
                    <nav class="navbar">
                        <ul class="navbar_menu">
                            <li><a href="@Url.Action("Index")">home</a></li>
                            <li><a href="@Url.Action("Contact")">contact</a></li>
                        </ul>
                        <ul class="navbar_user">
                            <li><a href="@Url.Action("Filter")"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                            <li><a href="https://localhost:44357/Home/TTKhach?idKH=@ViewBag.IdKH"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                            <li class="checkout">
                                <a href="https://localhost:44357/Home/GioHang?idKH=@ViewBag.IdKH">
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                    <span id="checkout_items" class="checkout_items">2</span>
                                </a>
                            </li>
                        </ul>
                        <div class="hamburger_container">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container contact_container">
    <div class="row">
        <div class="col">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">

            </div>

        </div>
    </div>

    <!-- Map Container -->

    <div class="row">
        <div class="col">
            <div id="google_map">
                <div id="map"></div>
                <pre id="coordinates" class="coordinates"></pre>
                <ul id="buttons">
                    <li id="button-vi" class="button">Vietnam</li>
                    <li id="button-de" class="button">German</li>
                    <li id="button-es" class="button">Spanish</li>
                    <li id="button-en" class="button">English</li>
                </ul>
                <script>
                    mapboxgl.accessToken = 'pk.eyJ1IjoiZG90aGlsb2FuIiwiYSI6ImNsMW9xNTduaDBtdm4zZXBnb3p5ZnV0NDcifQ.KmmJaDCnbdYUCrmuiLUnFg';
                    const coordinates = document.getElementById('coordinates');
                    const map = new mapboxgl.Map({
                        container: 'map',
                        style: 'mapbox://styles/mapbox/streets-v11',
                        center: [105.85, 21.0], //Tọa độ lãnh thổ Việt Nam
                        zoom: 2 //tỷ lê phóng của bản đồ
                    });//tải bản đồ lên website


                    //thêm một marker
                    const marker = new mapboxgl.Marker({
                        color: "red",
                        draggable: true
                    })
                        .setLngLat([105.85, 21.0])  //thiết lập vị trí hiển thị
                        .addTo(map);

                    //hàm hiển thị tọa độ khi kết thúc sự kiện kéo marker
                    function onDragEnd() {
                        const lngLat = marker.getLngLat();
                        coordinates.style.display = 'block';
                        coordinates.innerHTML = `Longitude: ${lngLat.lng}<br />Latitude: ${lngLat.lat}`;
                    }
                    marker.on('dragend', onDragEnd);

                    //Thêm popup
                    var popup = new mapboxgl.Popup({
                        closeButton: true,
                        closeOnClick: false,
                        anchor: 'right',
                    }).setLngLat([105.85, 21.0])
                        .setHTML("<h6>Hà Nội</h6>")
                        .addTo(map);

                    //Thêm nút phóng to, thu nhỏ và la bàn
                    map.addControl(new mapboxgl.NavigationControl({
                        showCompass: true,
                        showZoom: true,

                    }));

                    //Thêm định vị
                    map.addControl(new mapboxgl.GeolocateControl({
                        positionOptions: {
                            enableHighAccuracy: true
                        },
                        trackUserLocation: true
                    }));

                    //Thêm Tỉ lệ khoảng cách của bản đồ so với thực tế
                    var scale = new mapboxgl.ScaleControl({
                        maxWidth: 80,
                        unit: 'imperial'
                    });
                    map.addControl(scale);
                    scale.setUnit('metric');

                    //Thêm chế độ toàn màn hình
                    map.addControl(new mapboxgl.FullscreenControl());

                    //Chỉ dẫn đường trên bản đồ
                    map.addControl(
                        new MapboxDirections({
                            accessToken: mapboxgl.accessToken
                        }),
                        'top-left'
                    );

                    map.on('click', function (e) {
                        var popup = new mapboxgl.Popup({
                            closeButton: true,
                            closeOnClick: true,

                        }).setLngLat([e.lngLat.lng, e.lngLat.lat])
                            .setHTML("<h6>vị trí nhấn là: " + e.lngLat + "</h6>")
                            .addTo(map);
                    });

                    map.on('dblclick', function (e) {
                        new mapboxgl.Marker({
                            color: 'blue',
                            draggable: true,
                        }).setLngLat([e.lngLat.lng, e.lngLat.lat])
                            .addTo(map);
                    });

                    document.getElementById('buttons').addEventListener('click', (event) => {
                        const language = event.target.id.substr('button-'.length);
                        map.setLayoutProperty('country-label', 'text-field', [
                            'get',
                            `name_${language}`
                        ]);
                    });

                </script>
            </div>
        </div>
    </div>

    <!-- Contact Us -->

    <hr />
    <div class="row" style="margin-top: 20px">

        <div class="col-lg-6 contact_col">
            <div class="contact_contents">
                <h1>Contact Us</h1>
                <p>There are many ways to contact us. You may drop us a line, give us a call or send an email, choose what suits you the most.</p>
                <div>
                    <p>(800) 686-6688</p>
                    <p>info.deercreative@gmail.com</p>
                </div>
                <div>
                    <p>mm</p>
                </div>
                <div>
                    <p>Open hours: 8.00-18.00 Mon-Fri</p>
                    <p>Sunday: Closed</p>
                </div>
            </div>

            <!-- Follow Us -->

            <div class="follow_us_contents">
                <h1>Follow Us</h1>
                <ul class="social d-flex flex-row">
                    <li><a href="#" style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#" style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#" style="background-color: #fb4343"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#" style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>

        </div>

        <div class="col-lg-6 get_in_touch_col">
            <div class="get_in_touch_contents">
                <h1>Get In Touch With Us!</h1>
                <p>Fill out the form below to recieve a free and confidential.</p>
                <form action="post">
                    <div>
                        <input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="Name" required="required" data-error="Name is required.">
                        <input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
                        <input id="input_website" class="form_input input_website input_ph" type="url" name="name" placeholder="Website" required="required" data-error="Name is required.">
                        <textarea id="input_message" class="input_ph input_message" name="message" placeholder="Message" rows="3" required data-error="Please, write us a message."></textarea>
                    </div>
                    <div>
                        <button id="review_submit" type="submit" class="red_button message_submit_btn trans_300" value="Submit">send message</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<script src="~/Content/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/styles/bootstrap4/popper.js"></script>
<script src="~/Content/styles/bootstrap4/bootstrap.min.js"></script>
<script src="~/Content/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="~/Content/plugins/easing/easing.js"></script>
<script src="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="~/Content/js/contact_custom.js"></script>